<!-- <div class="footer">
				<p>
				</p>
				<a class="generator-sign" href="http://tubaina.sourceforge.net" title="generated by Tubaina" target="_blank">
					<img src="${relative}/includes/images/tubaina-icon.png" alt="generated by Tubaina" />
				</a>
				<br class="clear" />
			</div> 
											
		</div> 
		-->
	</body>
</html>