	
			
			<div class="footer">
				<p>
					<!-- info you'd like to present on footer -->
					
				</p>
				<a class="generator-sign" href="http://tubaina.sourceforge.net" title="generated by Tubaina" target="_blank">
					<img src="${relative}/includes/images/tubaina-icon.png" alt="generated by Tubaina" />
				</a>
				<br class="clear" />
			</div> <!-- footer -->	
											
		</div> <!-- content -->
		
	</body>
</html>