\thispagestyle{empty}

\vspace*{2.5cm}
\large \centerline{\bf ${book.name}}

\large
\vspace {1.3 cm}
\centerline{\bf <Any other info you might want to show>}

\normalsize
\vspace{2 cm}
\centerline{<more info>}
\vspace{0.1cm}
\vspace {0.3 cm}

\vspace{2.5cm}

\normalsize
\vspace {0.5 cm}
\begin{center}

Automatically generated by \href{http://sourceforge.net/projects/tubaina/}{Caelum Objects Tubaina} \\
\today

\end{center}

